server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: workflow-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${KAFKA_GROUP_ID:workflow-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.workflow.acl.event,com.workflow.*"
        spring.json.type.mapping: "com.workflow.acl.event.WorkflowCreationEvent:com.workflow.domain.event.WorkflowCreationEvent,event:com.workflow.domain.event.WorkflowStepEvent"
        spring.json.value.default.type: "com.workflow.domain.event.WorkflowStepEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/workflow_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kafka:
  topics:
    creation:
      request: ${KAFKA_TOPIC_CREATION_REQUEST:workflow.creation.request}
    step:
      request: ${KAFKA_TOPIC_STEP_REQUEST:workflow.step.request}
      response: ${KAFKA_TOPIC_STEP_RESPONSE:workflow.step.response}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true

logging:
  level:
    com.workflow: ${LOG_LEVEL:DEBUG}
